cloud:
  aws:
    credentials:
      access-key: AKIA6MKMVXIVQDXEMC6Y
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: securefilesystem
    
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB